-- {
--   "ms-jpq/coq_nvim",
--   config = function()
--     require("coq")
--   end,
--   dependencies = {
--     -- { "ms-jpq/coq.artifacts", branch = "artifacts" },
--     { "ms-jpq/coq.thirdparty", branch = "3p" },
--   },
-- }
